name: Generate GitHub Contribution Grid Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * SUN"

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: pattacini
          svg_out_path: github-user-contribution.svg

      - name: Update Repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          cd ${GITHUB_WORKSPACE}
          git clone https://github.com/${{ github.repository }}.git profile-repo
          mv github-user-contribution.svg profile-repo/assets
          cd profile-repo
          git commit -am "github-contribution-grid-snake updated"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push
